/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import DataBase.DB_Connection;
import java.sql.Connection;
import Library.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.swing.text.StyleConstants.Bold;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Catalin
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public HomePage() {
        
        
        
        initComponents();
        
        //Add book panel
        HomePanel.setVisible(true);
        BookUpdatePanel.setVisible(false);   
        BookAddPanel.setVisible(false);
        BookRemovePanel.setVisible(false);
        ReaderAddPanel.setVisible(false);
        ReaderUpdatePanel.setVisible(false);
        ReaderRemovePanel.setVisible(false);
        
        
        this.setTitle("Home page");
        
        // <editor-fold defaultstate="collapsed" desc="update book panel">
        
        UpdateBook.setEnabled(false);
        NewBookID.setEnabled(false);
        NewBookName.setEnabled(false);
        NewBookAuthor.setEnabled(false);
        NewBookType.setEnabled(false);
        // </editor-fold>  
        
        addWindowListener(new WindowAdapter() {
  public void windowClosing(WindowEvent e) {
    int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to exit the program?", "Exit Program Message Box",
        JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      System.exit(confirmed);
    }
  }
});
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookAddPanel = new javax.swing.JPanel();
        BookID = new javax.swing.JTextField();
        BookName = new javax.swing.JTextField();
        BookAuthor = new javax.swing.JTextField();
        BookType = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        AddBook = new java.awt.Button();
        BookUpdatePanel = new javax.swing.JPanel();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        UpdateBook = new java.awt.Button();
        NewBookID = new javax.swing.JTextField();
        NewBookName = new javax.swing.JTextField();
        NewBookAuthor = new javax.swing.JTextField();
        NewBookType = new javax.swing.JTextField();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        UpdatedBookID = new javax.swing.JTextField();
        CheckBookID = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        BookRemovePanel = new javax.swing.JPanel();
        label12 = new java.awt.Label();
        DeletedBookID = new javax.swing.JTextField();
        CheckBookID1 = new javax.swing.JCheckBox();
        label13 = new java.awt.Label();
        DeleteBook = new java.awt.Button();
        HomePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        ReaderAddPanel = new javax.swing.JPanel();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        AddReader = new java.awt.Button();
        ReaderID = new javax.swing.JTextField();
        ReaderCNP = new javax.swing.JTextField();
        ReaderName = new javax.swing.JTextField();
        ReaderGroup = new javax.swing.JTextField();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        ReaderUpdatePanel = new javax.swing.JPanel();
        ReaderRemovePanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Pages = new javax.swing.JMenu();
        Home = new javax.swing.JMenuItem();
        Options = new javax.swing.JMenu();
        Book = new javax.swing.JMenu();
        Add_Book = new javax.swing.JMenuItem();
        Update_Book = new javax.swing.JMenuItem();
        Remove_Book = new javax.swing.JMenuItem();
        Reader = new javax.swing.JMenu();
        Add_Reader = new javax.swing.JMenuItem();
        Update_Reader = new javax.swing.JMenuItem();
        Remove_Reader = new javax.swing.JMenuItem();
        View = new javax.swing.JMenuItem();
        Actions = new javax.swing.JMenu();
        Refresh = new javax.swing.JMenuItem();
        Quit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(650, 300));
        setResizable(false);

        BookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIDActionPerformed(evt);
            }
        });

        label1.setText("Book ID");

        label2.setText("Book Name");

        label3.setText("Book Author");

        label4.setText("Book Type");

        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setText("Add a new book...");

        AddBook.setLabel("Add Book");
        AddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookAddPanelLayout = new javax.swing.GroupLayout(BookAddPanel);
        BookAddPanel.setLayout(BookAddPanelLayout);
        BookAddPanelLayout.setHorizontalGroup(
            BookAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookAddPanelLayout.createSequentialGroup()
                .addGroup(BookAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BookAddPanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddBook, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BookAddPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(BookAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookType)
                            .addComponent(BookAuthor)
                            .addComponent(BookName)
                            .addComponent(BookID))))
                .addGap(112, 112, 112))
        );
        BookAddPanelLayout.setVerticalGroup(
            BookAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookAddPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(BookAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(BookAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        label6.setText("New Book Author");

        label7.setText("New Book Type");

        label8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label8.setText("Update a Book...");

        UpdateBook.setLabel("Update Book");
        UpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBookActionPerformed(evt);
            }
        });

        label9.setText("New Book ID");

        label10.setText("New Book Name");

        label11.setAlignment(java.awt.Label.CENTER);
        label11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label11.setText("Book ID for Update");

        CheckBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBookIDActionPerformed(evt);
            }
        });

        jTextPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextPane1.setText("Complete thisfield first !");
        jTextPane1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jTextPane1.setEnabled(false);
        jTextPane1.setOpaque(false);
        jScrollPane2.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextPane2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextPane2.setText("Complete only the fields to be changed !");
        jTextPane2.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jTextPane2.setEnabled(false);
        jTextPane2.setOpaque(false);
        jScrollPane3.setViewportView(jTextPane2);

        javax.swing.GroupLayout BookUpdatePanelLayout = new javax.swing.GroupLayout(BookUpdatePanel);
        BookUpdatePanel.setLayout(BookUpdatePanelLayout);
        BookUpdatePanelLayout.setHorizontalGroup(
            BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookUpdatePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookUpdatePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookUpdatePanelLayout.createSequentialGroup()
                        .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BookUpdatePanelLayout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateBook, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addGroup(BookUpdatePanelLayout.createSequentialGroup()
                                .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(BookUpdatePanelLayout.createSequentialGroup()
                                        .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BookUpdatePanelLayout.createSequentialGroup()
                                                .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(UpdatedBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CheckBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NewBookID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NewBookType, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NewBookAuthor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NewBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(84, 84, 84))))
        );
        BookUpdatePanelLayout.setVerticalGroup(
            BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookUpdatePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookUpdatePanelLayout.createSequentialGroup()
                        .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookUpdatePanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(NewBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookUpdatePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewBookType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BookUpdatePanelLayout.createSequentialGroup()
                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBookID)
                            .addComponent(UpdatedBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
        );

        label12.setAlignment(java.awt.Label.CENTER);
        label12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label12.setText("Book ID for Remove");

        CheckBookID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBookID1ActionPerformed(evt);
            }
        });

        label13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label13.setText("Remove a Book...");

        DeleteBook.setEnabled(false);
        DeleteBook.setLabel("Remove Book");
        DeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookRemovePanelLayout = new javax.swing.GroupLayout(BookRemovePanel);
        BookRemovePanel.setLayout(BookRemovePanelLayout);
        BookRemovePanelLayout.setHorizontalGroup(
            BookRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookRemovePanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(label13, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(159, 159, 159))
            .addGroup(BookRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookRemovePanelLayout.createSequentialGroup()
                    .addGroup(BookRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BookRemovePanelLayout.createSequentialGroup()
                            .addGap(198, 198, 198)
                            .addComponent(DeletedBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookRemovePanelLayout.createSequentialGroup()
                            .addGap(204, 204, 204)
                            .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(CheckBookID1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(198, Short.MAX_VALUE)))
        );
        BookRemovePanelLayout.setVerticalGroup(
            BookRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookRemovePanelLayout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addGroup(BookRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addGroup(BookRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookRemovePanelLayout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(BookRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CheckBookID1)
                        .addComponent(DeletedBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(145, Short.MAX_VALUE)))
        );

        jEditorPane1.setEditable(false);
        jEditorPane1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jEditorPane1.setText("          \t\t\n\n          This is  java college project application !\n          For any future problem contact an admin !\n          Admins :\n\t->Georgescu Catalin-Marian \n\t->Ibis Alexandra Elena\n\t->Tiper Alexandru\n          \t\tGroup : 251\n");
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );

        label14.setText("Reader Group");

        label15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label15.setText("Add a new reader...");

        AddReader.setLabel("Add Reader");
        AddReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddReaderActionPerformed(evt);
            }
        });

        label16.setText("Reader ID");

        label17.setText("Reader CNP");

        label18.setText("Reader Name");

        javax.swing.GroupLayout ReaderAddPanelLayout = new javax.swing.GroupLayout(ReaderAddPanel);
        ReaderAddPanel.setLayout(ReaderAddPanelLayout);
        ReaderAddPanelLayout.setHorizontalGroup(
            ReaderAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReaderAddPanelLayout.createSequentialGroup()
                .addGroup(ReaderAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ReaderAddPanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddReader, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ReaderAddPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(ReaderAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label18, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(label14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReaderAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReaderGroup)
                            .addComponent(ReaderName)
                            .addComponent(ReaderCNP)
                            .addComponent(ReaderID))))
                .addGap(112, 112, 112))
        );
        ReaderAddPanelLayout.setVerticalGroup(
            ReaderAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReaderAddPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(ReaderAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReaderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReaderAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReaderCNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReaderAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReaderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReaderAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReaderGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(ReaderAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddReader, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ReaderUpdatePanelLayout = new javax.swing.GroupLayout(ReaderUpdatePanel);
        ReaderUpdatePanel.setLayout(ReaderUpdatePanelLayout);
        ReaderUpdatePanelLayout.setHorizontalGroup(
            ReaderUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        ReaderUpdatePanelLayout.setVerticalGroup(
            ReaderUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ReaderRemovePanelLayout = new javax.swing.GroupLayout(ReaderRemovePanel);
        ReaderRemovePanel.setLayout(ReaderRemovePanelLayout);
        ReaderRemovePanelLayout.setHorizontalGroup(
            ReaderRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        ReaderRemovePanelLayout.setVerticalGroup(
            ReaderRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        Pages.setText("Pages");

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        Pages.add(Home);

        jMenuBar1.add(Pages);

        Options.setText("Options");

        Book.setText("Book");

        Add_Book.setText("Add");
        Add_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_BookActionPerformed(evt);
            }
        });
        Book.add(Add_Book);

        Update_Book.setText("Update");
        Update_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_BookActionPerformed(evt);
            }
        });
        Book.add(Update_Book);

        Remove_Book.setText("Remove");
        Remove_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_BookActionPerformed(evt);
            }
        });
        Book.add(Remove_Book);

        Options.add(Book);

        Reader.setText("Reader");

        Add_Reader.setText("Add");
        Add_Reader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ReaderActionPerformed(evt);
            }
        });
        Reader.add(Add_Reader);

        Update_Reader.setText("Update");
        Update_Reader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_ReaderActionPerformed(evt);
            }
        });
        Reader.add(Update_Reader);

        Remove_Reader.setText("Remove");
        Remove_Reader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_ReaderActionPerformed(evt);
            }
        });
        Reader.add(Remove_Reader);

        Options.add(Reader);

        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        Options.add(View);

        jMenuBar1.add(Options);

        Actions.setText("Actions");

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        Actions.add(Refresh);

        Quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        Actions.add(Quit);

        jMenuBar1.add(Actions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BookAddPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BookUpdatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BookRemovePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HomePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ReaderAddPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ReaderUpdatePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ReaderRemovePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BookAddPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BookUpdatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BookRemovePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ReaderAddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ReaderUpdatePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ReaderRemovePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Remove_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_BookActionPerformed
        BookRemovePanel.setVisible(true);
        BookAddPanel.setVisible(false);
        BookUpdatePanel.setVisible(false);
        HomePanel.setVisible(false);
        ReaderAddPanel.setVisible(false);
        ReaderUpdatePanel.setVisible(false);
        ReaderRemovePanel.setVisible(false);
        
        
    }//GEN-LAST:event_Remove_BookActionPerformed

    
    
    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        
    }//GEN-LAST:event_QuitActionPerformed

    private void Add_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_BookActionPerformed
        BookAddPanel.setVisible(true);
        BookUpdatePanel.setVisible(false);
        BookRemovePanel.setVisible(false);
        HomePanel.setVisible(false);
        ReaderAddPanel.setVisible(false);
        ReaderUpdatePanel.setVisible(false);
        ReaderRemovePanel.setVisible(false);
        
    }//GEN-LAST:event_Add_BookActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        
        
        view.setVisible(false);
        view=null;
        
        view=new View();
        
        view.setLocation(this.getX()+100, this.getY()+200);
        view.setVisible(true);
    }//GEN-LAST:event_ViewActionPerformed

    private void Update_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_BookActionPerformed
        BookUpdatePanel.setVisible(true);   
        BookAddPanel.setVisible(false);
        BookRemovePanel.setVisible(false);
        HomePanel.setVisible(false);
        ReaderAddPanel.setVisible(false);
        ReaderUpdatePanel.setVisible(false);
        ReaderRemovePanel.setVisible(false);
    }//GEN-LAST:event_Update_BookActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        HomePanel.setVisible(true);
        BookUpdatePanel.setVisible(false);   
        BookAddPanel.setVisible(false);
        BookRemovePanel.setVisible(false);
        ReaderAddPanel.setVisible(false);
        ReaderUpdatePanel.setVisible(false);
        ReaderRemovePanel.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        
       
        
        //refresh view
        view.setVisible(false);
        view=null;
        view=new View();
        view.setLocation(this.getX()+100, this.getY()+200);
        view.setVisible(true);
    }//GEN-LAST:event_RefreshActionPerformed

    private void AddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookActionPerformed
            String bookID=BookID.getText();
            String bookName=BookName.getText();
            String bookAuthor=BookAuthor.getText();
            String bookType=BookType.getText();
            boolean check=true;
            int iBookID=-100;//0 is too risky for a db
            try
            {
                 iBookID=Integer.parseInt(bookID);
            }
            catch(Exception e)
            {
                check=false;
            }
           
            
            if(bookID.equals("")||bookName.equals("")||bookAuthor.equals("")||bookType.equals(""))
            {
                
                JOptionPane.showMessageDialog (null, "Please complete all fields !"
                        , "Warning", JOptionPane.WARNING_MESSAGE);

                
            }
            else if(check==false)
                {
                    
                JOptionPane.showMessageDialog (null, "Id of the book must be an integer valid number !", "Warning", JOptionPane.WARNING_MESSAGE);

                }
            else if(Integer.parseInt(bookID)<1)
            {
                JOptionPane.showMessageDialog (null, 
                    "Book ID must be highere than 0 !", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else 
            {
                try
                {
                    Library.Book book = new Book(iBookID,bookName,bookAuthor,bookType);
                    
                    
                    
                    
                        
                    
                    
                    
                    
                    

                }
                catch(Exception e)
                {
                    
                    JOptionPane.showMessageDialog (null, "A seriosu problem has occured !\n"
                            +"Please contact an admin !", "Warning", JOptionPane.WARNING_MESSAGE);

                    
                }
            }
            
    
            
    }//GEN-LAST:event_AddBookActionPerformed

    
    // <editor-fold defaultstate="collapsed" desc="Update Button">  
    private void UpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBookActionPerformed
        if(CheckBookID.isSelected()==true)
        {
            try
            {
                Connection connection = DB_Connection.InitializeConnection();
                
                if(connection!=null)
                {
                    String updatedBookID = UpdatedBookID.getText();
                    
                    ResultSet resultSet = Library.Book.SearchBookByID(Integer.parseInt(updatedBookID));
                    
                    if(!resultSet.next())
                    {
                        JOptionPane.showMessageDialog (null,"Book not found !", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    else
                    {
                        boolean check=true;
                        try
                        {
                            int newBookIDCheck=Integer.parseInt(NewBookID.getText());
                            
                        }
                        catch(Exception e)
                        {
                            check=false;
                            System.out.println(check);
                          
                        }
                        
                        
                        String newBookID=NewBookID.getText();
                        String newBookName=NewBookName.getText();
                        String newBookAuthor=NewBookAuthor.getText();
                        String newBookType=NewBookType.getText();
                        
                            
                         if(NewBookID.getText().equals(""))
                         {
                            if(!newBookName.equals(""))
                            {
                                Library.Book.UpdateBookName(Integer.parseInt(updatedBookID), newBookName);
                            }
                            if(!newBookAuthor.equals(""))
                            {
                                Library.Book.UpdateBookAuthor(Integer.parseInt(updatedBookID), newBookAuthor);
                            }
                            if(!newBookType.equals(""))
                            {
                                Library.Book.UpdateBookType(Integer.parseInt(updatedBookID), newBookType);
                            }
                            JOptionPane.showMessageDialog (null,"   Book has been updated !", "", JOptionPane.INFORMATION_MESSAGE);
                            
                            /*DefaultTableModel model = (DefaultTableModel) view.jTable1.getModel();

                            int row=2;
                            for (int i = model.getRowCount() - 1; i >= 0; --i) {
                                for (int j = model.getColumnCount() - 1; j >= 0; --j) {
                                    if (model.getValueAt(i, j).equals(newBookID))
                                    {
                                        row=i;
                                    }
                                }
                            }
                            
                            view.jTable1.setValueAt(newBookID, 16, 1);*/
                            
                         }
                         else
                         {
                                if(check==false)
                                {
                                    JOptionPane.showMessageDialog (null,"   Invalid book ID !\n  The book has not been updated !", "Error", JOptionPane.WARNING_MESSAGE);
                                }
                                        else if(Integer.parseInt(newBookID)<1)
                                {
                                    JOptionPane.showMessageDialog (null,"The new book ID must be highere than 0 !\n The book has not been updated !", "Error", JOptionPane.WARNING_MESSAGE);
                                }
                                
                                else
                                {
                                    Library.Book book=Library.Book.ExtractBookDatas(Integer.parseInt(newBookID));
                                    if(book.GetBookID()!=0)
                                    {
                                        JOptionPane.showMessageDialog (null,"The Id is already used !", "Error", JOptionPane.WARNING_MESSAGE);
                                    }
                                    else
                                    {
                                        
                                        if(!newBookName.equals(""))
                                        {
                                        Library.Book.UpdateBookName(Integer.parseInt(updatedBookID), newBookName);
                                        }
                                        if(!newBookAuthor.equals(""))
                                        {
                                        Library.Book.UpdateBookAuthor(Integer.parseInt(updatedBookID), newBookAuthor);
                                        }
                                        if(!newBookType.equals(""))
                                        {
                                        Library.Book.UpdateBookType(Integer.parseInt(updatedBookID), newBookType);
                                        }
                                        if(!newBookID.equals(""))
                                        {
                                        Library.Book.UpdateBookID(Integer.parseInt(updatedBookID), Integer.parseInt(newBookID));
                                        }
                                        JOptionPane.showMessageDialog (null,"   Book has been updated !", "", JOptionPane.INFORMATION_MESSAGE);
                                        view.jTable1.updateUI();
                                    }
                                }
                                
                         }
                   
                    }
                    //DO the staff
                    
                    
                }
                //else nothing(the progrm manage the messages already)
            }
            catch(Exception ex)
            {
                
            }
        }
        else
        {
            //It is useless since the button is not enabled as log as the checkbox is not cheked
            JOptionPane.showMessageDialog (null, "Complete the BookID field and check the box !"
                    , "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_UpdateBookActionPerformed
// </editor-fold>  
    
    
    
    private void CheckBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBookIDActionPerformed
        
        int checkBookID;
        try
        {
            checkBookID = Integer.parseInt(UpdatedBookID.getText());

        }
        catch (NumberFormatException e)
        {
            checkBookID=-100;
        }
        System.out.println(checkBookID);
        if(checkBookID!=-100)
        {
            if( CheckBookID.isSelected()==true && !UpdatedBookID.getText().equals("") && Integer.parseInt(UpdatedBookID.getText())>0 )
        {
            
            
            UpdatedBookID.setEditable(false);
            UpdateBook.setEnabled(true);
            NewBookID.setEnabled(true);
            NewBookName.setEnabled(true);
            NewBookAuthor.setEnabled(true);
            NewBookType.setEnabled(true);
            
         
        }
        else if(checkBookID<0||UpdatedBookID.getText().equals("")||Integer.parseInt(UpdatedBookID.getText())<1)
        {
            CheckBookID.setSelected(false);
            UpdatedBookID.setEditable(true);
            UpdateBook.setEnabled(false);
            NewBookID.setEnabled(false);
            NewBookName.setEnabled(false);
            NewBookAuthor.setEnabled(false);
            NewBookType.setEnabled(false);
            
            
            if(UpdatedBookID.getText().equals(""))
            {
                JOptionPane.showMessageDialog (null, "Complete the BookID field !"
                    , "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else if(Integer.parseInt(UpdatedBookID.getText())<1)
            {
                
                JOptionPane.showMessageDialog (null, "Book ID must be highere than 0 !"
                    , "Warning", JOptionPane.WARNING_MESSAGE);
            }
           
            
            
        }
        else 
        {
            CheckBookID.setSelected(false);
            UpdatedBookID.setEditable(true);
            UpdateBook.setEnabled(false);
            NewBookID.setEnabled(false);
            NewBookName.setEnabled(false);
            NewBookAuthor.setEnabled(false);
            NewBookType.setEnabled(false);
            
            
            
        }
        }
        else
        {
            CheckBookID.setSelected(false);
            UpdatedBookID.setEditable(true);
            UpdateBook.setEnabled(false);
            NewBookID.setEnabled(false);
            NewBookName.setEnabled(false);
            NewBookAuthor.setEnabled(false);
            NewBookType.setEnabled(false);
            JOptionPane.showMessageDialog (null, "Invalid book ID !"
                    , "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        
        
            
    }//GEN-LAST:event_CheckBookIDActionPerformed

    private void CheckBookID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBookID1ActionPerformed
        int checkBookID;
        try
        {
            checkBookID=Integer.parseInt(DeletedBookID.getText());
        }
        catch (NumberFormatException e)
        {
            checkBookID=-100;
        }
        
        
        
        if(checkBookID!=-100)
        {
            if(CheckBookID1.isSelected()==true && Integer.parseInt(DeletedBookID.getText())>0)
            {
                 
                    DeleteBook.setEnabled(true);
                    DeletedBookID.setEnabled(false);
                  
            }
            else if(CheckBookID1.isSelected()==true)
            {
                DeleteBook.setEnabled(false);
                DeletedBookID.setEnabled(true);
                JOptionPane.showMessageDialog (null, "Book ID must be higher than 0 ! "
                    , "Error", JOptionPane.WARNING_MESSAGE);
                
            }
            else
            {
                DeleteBook.setEnabled(false);
                DeletedBookID.setEnabled(true);
            }
        }
        else
        {
                DeleteBook.setEnabled(false);
                DeletedBookID.setEnabled(true);
                CheckBookID1.setSelected(false);
                JOptionPane.showMessageDialog (null, "Invalid Book ID ! \n "
                    , "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_CheckBookID1ActionPerformed

    private void DeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookActionPerformed
        try
        {
            ResultSet resultSet=Library.Book.SearchBookByID(Integer.parseInt(DeletedBookID.getText()));
            if(resultSet.next())
            {
                Library.Book.DeletBook(Integer.parseInt(DeletedBookID.getText()));
            }
            else
            {
                JOptionPane.showMessageDialog (null, "Book not found !", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (SQLException ex)
        {
            //System.out.println("Here");
            //Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteBookActionPerformed

    private void Add_ReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ReaderActionPerformed
        
        ReaderAddPanel.setVisible(true);
        HomePanel.setVisible(false);
        BookUpdatePanel.setVisible(false);   
        BookAddPanel.setVisible(false);
        BookRemovePanel.setVisible(false);
        ReaderUpdatePanel.setVisible(false);
        ReaderRemovePanel.setVisible(false);
    }//GEN-LAST:event_Add_ReaderActionPerformed

    private void Update_ReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ReaderActionPerformed
        
        ReaderUpdatePanel.setVisible(true);
        ReaderAddPanel.setVisible(false);
        HomePanel.setVisible(false);
        BookUpdatePanel.setVisible(false);   
        BookAddPanel.setVisible(false);
        BookRemovePanel.setVisible(false);
        ReaderRemovePanel.setVisible(false);
    }//GEN-LAST:event_Update_ReaderActionPerformed

    private void Remove_ReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_ReaderActionPerformed
        
        ReaderRemovePanel.setVisible(true);
        ReaderUpdatePanel.setVisible(false);
        ReaderAddPanel.setVisible(false);
        HomePanel.setVisible(false);
        BookUpdatePanel.setVisible(false);   
        BookAddPanel.setVisible(false);
        BookRemovePanel.setVisible(false);
        
    }//GEN-LAST:event_Remove_ReaderActionPerformed

    private void AddReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddReaderActionPerformed
            String readerID=ReaderID.getText();
            String readerName=ReaderName.getText();
            String readerCNP=ReaderCNP.getText();
            String readerGroup=ReaderGroup.getText();
            boolean checkID=true;
            boolean checkGroup=true;
            
            
            
            int iReaderID=-100;//0 is too risky for a db
            
            int iReaderGroup=-100;
            
            
            //check that reader ID is integer
            try
            {
                 iReaderID=Integer.parseInt(readerID);
            }
            catch(Exception e)
            {
                checkID=false;
            }
           
            
            
            
            //check that reader Group is integer
            try
            {
                 iReaderGroup=Integer.parseInt(readerGroup);
            }
            catch(Exception e)
            {
                checkGroup=false;
            }
            
            
            
            if(readerID.equals("")||readerName.equals("")||readerGroup.equals("")||readerCNP.equals(""))
            {
                
                JOptionPane.showMessageDialog (null, "Please complete all fields !"
                        , "Warning", JOptionPane.WARNING_MESSAGE);

                
            }//check reader ID validity
            else if(checkID==false)
                {
                    
                JOptionPane.showMessageDialog (null, "Id of the reader must be an integer valid number !", "Warning", JOptionPane.WARNING_MESSAGE);

                }
            else if(Integer.parseInt(readerID)<1)
            {
                JOptionPane.showMessageDialog (null, 
                    "Reader ID must be highere than 0 !", "Warning", JOptionPane.WARNING_MESSAGE);
            }//check reader CNP validity
            
            else if(checkGroup==false)
                {
                    
                JOptionPane.showMessageDialog (null, "Group of the reader must be an integer valid number !", "Warning", JOptionPane.WARNING_MESSAGE);

                }
            else if(Integer.parseInt(readerGroup)<1)
            {
                JOptionPane.showMessageDialog (null, 
                    "Reader Group must be highere than 0 !", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else 
            {
                try
                {
                    Library.Reader reader = new Reader(iReaderID,readerCNP,readerName,iReaderGroup);
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    

                }
                catch(Exception e)
                {
                    
                    JOptionPane.showMessageDialog (null, "A seriosu problem has occured !\n"
                            +"Please contact an admin !", "Warning", JOptionPane.WARNING_MESSAGE);

                    
                }
            }
    }//GEN-LAST:event_AddReaderActionPerformed

    private void BookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookIDActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
                
                
            }
        });
        
        
      
        
    }
    
    public static  View view = new View();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Actions;
    private java.awt.Button AddBook;
    private java.awt.Button AddReader;
    private javax.swing.JMenuItem Add_Book;
    private javax.swing.JMenuItem Add_Reader;
    private javax.swing.JMenu Book;
    private javax.swing.JPanel BookAddPanel;
    private javax.swing.JTextField BookAuthor;
    private javax.swing.JTextField BookID;
    private javax.swing.JTextField BookName;
    private javax.swing.JPanel BookRemovePanel;
    private javax.swing.JTextField BookType;
    private javax.swing.JPanel BookUpdatePanel;
    private javax.swing.JCheckBox CheckBookID;
    private javax.swing.JCheckBox CheckBookID1;
    private java.awt.Button DeleteBook;
    private javax.swing.JTextField DeletedBookID;
    private javax.swing.JMenuItem Home;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JTextField NewBookAuthor;
    private javax.swing.JTextField NewBookID;
    private javax.swing.JTextField NewBookName;
    private javax.swing.JTextField NewBookType;
    private javax.swing.JMenu Options;
    private javax.swing.JMenu Pages;
    private javax.swing.JMenuItem Quit;
    private javax.swing.JMenu Reader;
    private javax.swing.JPanel ReaderAddPanel;
    private javax.swing.JTextField ReaderCNP;
    private javax.swing.JTextField ReaderGroup;
    private javax.swing.JTextField ReaderID;
    private javax.swing.JTextField ReaderName;
    private javax.swing.JPanel ReaderRemovePanel;
    private javax.swing.JPanel ReaderUpdatePanel;
    private javax.swing.JMenuItem Refresh;
    private javax.swing.JMenuItem Remove_Book;
    private javax.swing.JMenuItem Remove_Reader;
    private java.awt.Button UpdateBook;
    private javax.swing.JMenuItem Update_Book;
    private javax.swing.JMenuItem Update_Reader;
    private javax.swing.JTextField UpdatedBookID;
    private javax.swing.JMenuItem View;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
